### ISSUE TITLE
Add hierarchy?

### ISSUE THREAD

**Issue by kasemir** [sasaki77/alarm-test-script#1]
This is a good plain performance test, to see how the alarm server & GUI run with 50000 PVs.
It demonstrates that it basically "works", with CPU load mostly in the soft IOC, and brief spikes every ~30 seconds when 200 PVs go in/out of alarm.

For the intended use of the alarm tools, every alarm is something that a human needs to address, so it comes with some guidance and at least one link to a related displays. If no human was required, the response could be automated and the PV would not need to be in the alarm system. See also  alarm guidelines on https://controlssoftware.sns.ornl.gov/training/2019_USPAS

To make this demo more realistic, it makes sense to arrange the alarms in a hierarchy instead of a flat list.
For example, group 100 trigger PVs together, and arrange those into areas, sub and sub-sub groups:
```
/Area0/Sub0/SubSub0xx/Alarm00000
...
/Area0/Sub0/SubSub0xx/Alarm00099
/Area0/Sub0/SubSub1xx/Alarm00100
...
/Area0/Sub0/SubSub1xx/Alarm00199
...
/Area1/Sub2/SubSub0xx/Alarm12099
...
/Area4/Sub9/SubSub9xx/Alarm49999
```

This would be closer to a practical setup, where there would then be some guidance & screen links for each area, sub and sub-sub group, and the test would show how the alarms are summarized (maximized) up the tree structure.
In a real example, one might not be able to assign guidance and related displays to every trigger PV, but it's relatively easy in an arrangement like "FrontEnd/Vacuum/Pumps" to have information for the front end area, links to vacuum displays and guidance with vacuum personnel phone numbers, and then some detail links to the vacuum pumps.

**Comment by sasaki77** [comment]
Thank you for clarifying the alarm usage. I have added hierarchy for alarm configuration file.

You can see example files from `tests` directory. I'd really appreciated if you confirmed the hierarchy is configured as you thought.

https://github.com/sasaki77/alarm-test-script/blob/main/tests/alarm-config.xml

**Comment by kasemir** [comment]
Yes, that looks good, thank you!
